import type { Metadata } from 'next'
import { Footer } from '@/components/footer'
import { Header } from '@/components/header'
import '../shared/styles/global.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="ru">
			<body className="antialiased animate-fadeIn">
				<Header />
				<div className="px-[15px] lg:px-[25px] 2xl:px-[50px]">
					{children}

					<Footer />
				</div>
			</body>
		</html>
	)
}
